-- =====================================================
-- デモ用: RLSを一時的に無効化
-- 本番環境では使用しないでください
-- =====================================================

-- 各テーブルのRLSを無効化
ALTER TABLE tenants DISABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE subcontractors DISABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_subcontractors DISABLE ROW LEVEL SECURITY;
ALTER TABLE projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE job_posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE job_slots DISABLE ROW LEVEL SECURITY;
ALTER TABLE slot_applications DISABLE ROW LEVEL SECURITY;
ALTER TABLE nominated_subcontractors DISABLE ROW LEVEL SECURITY;
ALTER TABLE completion_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE evaluations DISABLE ROW LEVEL SECURITY;
ALTER TABLE monthly_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE csv_import_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE admin_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE master_trades DISABLE ROW LEVEL SECURITY;
ALTER TABLE master_areas DISABLE ROW LEVEL SECURITY;
